# Generated by Django 5.0.6 on 2025-10-31 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_stripe_session_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="color",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="size",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
